### PR TITLE
Use black (https://github.com/ambv/black) to enforce style

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by tomwhite** [comment]
This failed (intentionally) since the source doesn't conform to black style (see #14). The next step is to reformat all the source.

**Comment by tomwhite** [comment]
I've now reformatted the source in this PR. Does this look OK @ryan-williams?

**Comment by ryan-williams** [comment]
I'm ambivalent about this. lgtm if it's net-positive to you!

**Comment by tomwhite** [comment]
No rush on this - it was more of an experiment. I'm using something similar in the Java world (https://github.com/coveo/fmt-maven-plugin), which is useful for avoiding arguments on how things should be formatted. I'm not so familiar with all the Python conventions, so I thought it would be useful to have something that applies them without us having to think too hard.

**Comment by ryan-williams** [comment]
Makes sense, I'm more "+0" than "-0"

Mostly I think editors should show different people code however they like it formatted, but seems we're far from that world 😞

Looking at these again, I like them all except [this one](https://github.com/lasersonlab/single-cell-experiments/pull/27/files#diff-b15131236e6c2c6fbd87ed7939055ddeR47), which isn't a huge deal, so I'll go ahead and merge, thanks!

**Comment by tomwhite** [comment]
> Mostly I think editors should show different people code however they like it formatted

+1

**Pull request merged**
