### PR TITLE
travisci, circleci configs

### PR DESCRIPTION
**Pull request by ryan-williams**
also fix some `anndata` imports that i think were broken in the recent file moves

### CODE REVIEW

**Comment by ryan-williams** [comment]
some reflections:
- getting the `src/anndata` submodule to work required some hacking on each side; surprisingly not smooth
- circleci builds are extremely fast
  - start almost immediately
  - finish in ~1min (~4mins for travis)
  - ~40s of that is spinning up [a custom docker image](https://hub.docker.com/r/hancheng/circleci-python3.6-java8/) ([that I had to use to get both python and java](https://discuss.circleci.com/t/recommended-way-to-use-multiple-languages-in-2-0/14174))
    - [when i was using a stock circleci image, this step took <1s](https://circleci.com/gh/ryan-williams/single-cell-experiments/4)
    - will be good to look into caching the image or speeding that part up… 10-20s CI turnaround would be amazing
- i don't think travis is correctly caching the installed pip modules yet, but perhaps once this is merged then subsequent PRs will?

**Comment by ryan-williams** [comment]
It already was under `src/anndata`, but somehow the `.gitmodules` file had the wrong mapping.

It seems useful to have it under `src` so that we can explicitly import from the submodule, whereas `import anndata` would be ambiguous otherwise

**Comment by tomwhite** [comment]
Ah, I moved it to top-level `anndata` in https://github.com/lasersonlab/single-cell-experiments/commit/cce0e7cc62d6b3520aa9839eda4acabeb75b06ea since that is more conventional. I think we always want to import from the submodule, so it shouldn't be a problem. (Also, you can do `pip install ./anndata` to install the submodule, and `pip install anndata` to install the regular one.)

**Comment by ryan-williams** [comment]
```
$ git mv src/anndata anndata
$ python test_scanpy_spark.py
Traceback (most recent call last):
  File "test_scanpy_spark.py", line 1, in <module>
    import anndata.anndata as ad
ModuleNotFoundError: No module named 'anndata.anndata'
```

`python -c 'import anndata; print(anndata.__file__)'` shows that it's picking up `anndata` from my venv's `site-packages`.

I think I got things working using `export PYTHONPATH=anndata`, which also allows removing the extra layer of `anndata` indirection in our imports, so that a pip-installed version would be a drop-in replacement, which seems good; will push that here and see if I can make the CIs happy.

Is there an easier way to get this working?

**Pull request merged**
